export const navLinks = [
    { id: 'home', to: '/', label: 'Home', label2: 'Home', title: 'Ir al inicio', dataLink: 'navbar-inicio-link', dataLink2: 'footer-inicio-link' },
    {
        id: 'servicios',
        to: '#servicios',
        label: 'Servicios',
        label2: 'Servicios',
        title: 'Conoce los servicios de ortodoncia',
        dataLink: 'navbar-servicios-link',
        dataLink2: 'footer-servicios-link',
    },
    {
        id: 'nosotros',
        to: '#nosotros',
        label: 'Nosotros',
        label2: 'Nosotros',
        title: 'Conoce a los especialistas en ortodoncia',
        dataLink: 'navbar-nosotros-link',
        dataLink2: 'footer-nosotros-link',
    },
    {
        id: 'contacto',
        to: '#contacto',
        label: 'Contacto',
        label2: 'Contacto',
        title: 'Contactate con ortodoncia',
        dataLink: 'navbar-contacto-link',
        dataLink2: 'footer-contacto-link',
    },
];
